"""Built-in cover templates: classic text overlays first, then 抠像 styles."""

from __future__ import annotations


def _subject(
    *,
    enabled: bool = True,
    bg_mode: str = "blur",
    blur_radius: int = 56,
    outline: str = "solid",
    outline_color: str = "#FFFFFF",
    outline_width: int = 10,
    glow_color: str = "#FFFFFF",
    scale: float = 1.0,
    fill_ratio: float = 0.5,
    x_offset: float = -0.06,
    y_offset: float = 0.08,
) -> dict:
    return {
        "enabled": enabled,
        "bg_mode": bg_mode,
        "blur_radius": blur_radius,
        "outline": outline,
        "outline_color": outline_color,
        "outline_width": outline_width,
        "glow_color": glow_color,
        "scale": scale,
        "fill_ratio": fill_ratio,
        "x_offset": x_offset,
        "y_offset": y_offset,
    }


def _off() -> dict:
    return _subject(enabled=False)


# Classic (no cutout) — 参考短视频封面：大黄字阴影 / 倾斜黄白描边 / 白字粉描边
_CLASSIC: list[dict] = [
    {
        "id": "dy_hook_yellow",
        "name": "大黄字居中",
        "builtin": True,
        "subject": _off(),
        "background": {"overlay": "none", "overlay_alpha": 0},
        "layers": [
            {
                "id": "title",
                "type": "text",
                "label": "主标题",
                "text": "{{title}}",
                "x": 0.5,
                "y": 0.42,
                "anchor": "center",
                "font_size_ratio": 0.13,
                "font_weight": "bold",
                "color": "#FACC15",
                "stroke_color": "#0A0A0A",
                "stroke_width": 6,
                "effect": "shadow",
                "max_width_ratio": 0.72,
                "max_lines": 2,
                "band_height_ratio": 0.36,
                "rotation": 0,
            },
            {
                "id": "subtitle",
                "type": "text",
                "label": "副标题",
                "text": "{{subtitle}}",
                "x": 0.5,
                "y": 0.88,
                "anchor": "bottom_center",
                "font_size_ratio": 0.034,
                "font_weight": "bold",
                "color": "#FFFFFF",
                "stroke_color": "#111111",
                "stroke_width": 4,
                "effect": "outline",
                "max_width_ratio": 0.86,
                "max_lines": 1,
                "band_height_ratio": 0.08,
                "rotation": 0,
            },
        ],
    },
    {
        "id": "dy_tilt_duo",
        "name": "倾斜黄白双行",
        "builtin": True,
        "subject": _off(),
        "background": {"overlay": "dark_flat", "overlay_alpha": 55},
        "layers": [
            {
                "id": "title",
                "type": "text",
                "label": "主标题",
                "text": "{{title}}",
                "x": 0.48,
                "y": 0.4,
                "anchor": "center",
                "font_size_ratio": 0.078,
                "font_weight": "bold",
                "color": "#FDE047",
                "stroke_color": "#0A0A0A",
                "stroke_width": 7,
                "effect": "outline",
                "max_width_ratio": 0.88,
                "max_lines": 1,
                "band_height_ratio": 0.14,
                "rotation": -16,
            },
            {
                "id": "subtitle",
                "type": "text",
                "label": "副标题",
                "text": "{{subtitle}}",
                "x": 0.52,
                "y": 0.52,
                "anchor": "center",
                "font_size_ratio": 0.048,
                "font_weight": "bold",
                "color": "#FFFFFF",
                "stroke_color": "#0A0A0A",
                "stroke_width": 5,
                "effect": "outline",
                "max_width_ratio": 0.82,
                "max_lines": 1,
                "band_height_ratio": 0.1,
                "rotation": -16,
            },
        ],
    },
    {
        "id": "dy_pink_stroke",
        "name": "白字粉描边",
        "builtin": True,
        "subject": _off(),
        "background": {"overlay": "none", "overlay_alpha": 0},
        "layers": [
            {
                "id": "title",
                "type": "text",
                "label": "主标题",
                "text": "{{title}}",
                "x": 0.07,
                "y": 0.12,
                "anchor": "top_left",
                "font_size_ratio": 0.072,
                "font_weight": "bold",
                "color": "#FFFFFF",
                "stroke_color": "#EC4899",
                "stroke_width": 6,
                "effect": "outline",
                "max_width_ratio": 0.78,
                "max_lines": 2,
                "band_height_ratio": 0.2,
                "rotation": 0,
            },
            {
                "id": "subtitle",
                "type": "text",
                "label": "副标题",
                "text": "{{subtitle}}",
                "x": 0.07,
                "y": 0.3,
                "anchor": "top_left",
                "font_size_ratio": 0.038,
                "font_weight": "bold",
                "color": "#FFFFFF",
                "stroke_color": "#DB2777",
                "stroke_width": 4,
                "effect": "outline",
                "max_width_ratio": 0.78,
                "max_lines": 1,
                "band_height_ratio": 0.08,
                "rotation": 0,
            },
        ],
    },
    {
        "id": "dy_bottom_white",
        "name": "底栏白字描边",
        "builtin": True,
        "subject": _off(),
        "background": {"overlay": "bottom_gradient", "overlay_alpha": 200},
        "layers": [
            {
                "id": "title",
                "type": "text",
                "label": "主标题",
                "text": "{{title}}",
                "x": 0.5,
                "y": 0.78,
                "anchor": "bottom_center",
                "font_size_ratio": 0.056,
                "font_weight": "bold",
                "color": "#FFFFFF",
                "stroke_color": "#0A0A0A",
                "stroke_width": 5,
                "effect": "outline",
                "max_width_ratio": 0.9,
                "max_lines": 2,
                "band_height_ratio": 0.16,
                "rotation": 0,
            },
            {
                "id": "subtitle",
                "type": "text",
                "label": "副标题",
                "text": "{{subtitle}}",
                "x": 0.5,
                "y": 0.84,
                "anchor": "top_center",
                "font_size_ratio": 0.03,
                "font_weight": "bold",
                "color": "#FDE047",
                "stroke_color": "#0A0A0A",
                "stroke_width": 3,
                "effect": "outline",
                "max_width_ratio": 0.84,
                "max_lines": 1,
                "band_height_ratio": 0.07,
                "rotation": 0,
            },
        ],
    },
    {
        "id": "dy_hot_tag",
        "name": "角标+黄字底栏",
        "builtin": True,
        "subject": _off(),
        "background": {"overlay": "bottom_gradient", "overlay_alpha": 195},
        "layers": [
            {
                "id": "tag",
                "type": "text",
                "label": "角标",
                "text": "热卖",
                "x": 0.05,
                "y": 0.05,
                "anchor": "top_left",
                "font_size_ratio": 0.026,
                "font_weight": "bold",
                "color": "#111111",
                "stroke_color": "#000000",
                "stroke_width": 0,
                "effect": "pill",
                "pill_color": "#FDE047",
                "pill_alpha": 245,
                "max_width_ratio": 0.35,
                "max_lines": 1,
                "band_height_ratio": 0.05,
                "rotation": 0,
            },
            {
                "id": "title",
                "type": "text",
                "label": "主标题",
                "text": "{{title}}",
                "x": 0.5,
                "y": 0.76,
                "anchor": "bottom_center",
                "font_size_ratio": 0.058,
                "font_weight": "bold",
                "color": "#FACC15",
                "stroke_color": "#0A0A0A",
                "stroke_width": 5,
                "effect": "shadow",
                "max_width_ratio": 0.9,
                "max_lines": 2,
                "band_height_ratio": 0.14,
                "rotation": 0,
            },
            {
                "id": "subtitle",
                "type": "text",
                "label": "副标题",
                "text": "{{subtitle}}",
                "x": 0.5,
                "y": 0.82,
                "anchor": "top_center",
                "font_size_ratio": 0.028,
                "font_weight": "bold",
                "color": "#FFFFFF",
                "stroke_color": "#0A0A0A",
                "stroke_width": 3,
                "effect": "outline",
                "max_width_ratio": 0.84,
                "max_lines": 1,
                "band_height_ratio": 0.06,
                "rotation": 0,
            },
        ],
    },
    {
        "id": "dy_left_stack",
        "name": "左侧叠字",
        "builtin": True,
        "subject": _off(),
        "background": {"overlay": "dark_flat", "overlay_alpha": 40},
        "layers": [
            {
                "id": "title",
                "type": "text",
                "label": "主标题",
                "text": "{{title}}",
                "x": 0.06,
                "y": 0.62,
                "anchor": "top_left",
                "font_size_ratio": 0.062,
                "font_weight": "bold",
                "color": "#FDE047",
                "stroke_color": "#0A0A0A",
                "stroke_width": 5,
                "effect": "outline",
                "max_width_ratio": 0.7,
                "max_lines": 2,
                "band_height_ratio": 0.18,
                "rotation": 0,
            },
            {
                "id": "subtitle",
                "type": "text",
                "label": "副标题",
                "text": "{{subtitle}}",
                "x": 0.06,
                "y": 0.84,
                "anchor": "top_left",
                "font_size_ratio": 0.032,
                "font_weight": "bold",
                "color": "#FFFFFF",
                "stroke_color": "#0A0A0A",
                "stroke_width": 3,
                "effect": "outline",
                "max_width_ratio": 0.7,
                "max_lines": 2,
                "band_height_ratio": 0.1,
                "rotation": 0,
            },
        ],
    },
]

# 抠像 styles (rembg) — fewer, clearly named
_CUTOUT: list[dict] = [
    {
        # Tuned from user-saved「抠像·蓝虚线 · 副本」→ becomes the default builtin.
        "id": "cut_cyan_dash",
        "name": "抠像·蓝虚线",
        "builtin": True,
        "subject": _subject(
            outline="dashed",
            outline_color="#5EEAD4",
            outline_width=9,
            blur_radius=64,
            fill_ratio=0.77,
            x_offset=-0.25,
            y_offset=0.2,
        ),
        "background": {"overlay": "none", "overlay_alpha": 0},
        "layers": [
            {
                "id": "title",
                "type": "text",
                "label": "主标题",
                "text": "{{title}}",
                "depth": "behind",
                "writing_mode": "vertical",
                "x": 0.865,
                "y": 0.059,
                "anchor": "top_center",
                "font_size_ratio": 0.074,
                "font_weight": "bold",
                "color": "#0CEDDE",
                "stroke_color": "#0F172A",
                "stroke_width": 2,
                "effect": "shadow",
                "glow_color": "#22D3EE",
                "max_width_ratio": 0.26,
                "max_lines": 8,
                "band_height_ratio": 0.70,
            },
            {
                "id": "subtitle",
                "type": "text",
                "label": "副标题",
                "text": "{{subtitle}}",
                "depth": "behind",
                "writing_mode": "vertical",
                "x": 0.655,
                "y": 0.042,
                "anchor": "top_center",
                "font_size_ratio": 0.07,
                "font_weight": "normal",
                "color": "#3DD6CC",
                "stroke_color": "#0F172A",
                "stroke_width": 1,
                "effect": "shadow",
                "glow_color": "#22D3EE",
                "max_width_ratio": 0.33,
                "max_lines": 8,
                "band_height_ratio": 0.55,
            },
        ],
    },
    {
        "id": "cut_big_yellow",
        "name": "抠像·大黄字",
        "builtin": True,
        "subject": _subject(outline="solid", outline_color="#FFFFFF", outline_width=11, blur_radius=60, fill_ratio=0.52),
        "background": {"overlay": "none", "overlay_alpha": 0},
        "layers": [
            {
                "id": "title",
                "type": "text",
                "label": "主标题",
                "text": "{{title}}",
                "depth": "behind",
                "writing_mode": "vertical",
                "x": 0.16,
                "y": 0.1,
                "anchor": "top_center",
                "font_size_ratio": 0.085,
                "font_weight": "bold",
                "color": "#FDE047",
                "stroke_color": "#111111",
                "stroke_width": 6,
                "effect": "outline",
                "max_width_ratio": 0.35,
                "max_lines": 8,
                "band_height_ratio": 0.65,
            },
            {
                "id": "subtitle",
                "type": "text",
                "label": "副标题",
                "text": "{{subtitle}}",
                "depth": "front",
                "x": 0.5,
                "y": 0.9,
                "anchor": "bottom_center",
                "font_size_ratio": 0.03,
                "font_weight": "bold",
                "color": "#FFFFFF",
                "stroke_color": "#000000",
                "stroke_width": 2,
                "effect": "shadow",
                "max_width_ratio": 0.88,
                "max_lines": 2,
                "band_height_ratio": 0.08,
            },
        ],
    },
    {
        "id": "cut_blur_bg",
        "name": "抠像·模糊背景",
        "builtin": True,
        "subject": _subject(outline="none", blur_radius=70, fill_ratio=0.55, scale=1.0),
        "background": {"overlay": "bottom_gradient", "overlay_alpha": 140},
        "layers": [
            {
                "id": "title",
                "type": "text",
                "label": "主标题",
                "text": "{{title}}",
                "depth": "front",
                "x": 0.5,
                "y": 0.8,
                "anchor": "bottom_center",
                "font_size_ratio": 0.048,
                "font_weight": "bold",
                "color": "#FFFFFF",
                "stroke_color": "#000000",
                "stroke_width": 3,
                "effect": "shadow",
                "max_width_ratio": 0.9,
                "max_lines": 2,
                "band_height_ratio": 0.12,
            },
            {
                "id": "subtitle",
                "type": "text",
                "label": "副标题",
                "text": "{{subtitle}}",
                "depth": "front",
                "x": 0.5,
                "y": 0.86,
                "anchor": "top_center",
                "font_size_ratio": 0.026,
                "font_weight": "normal",
                "color": "#E5E7EB",
                "stroke_color": "#000000",
                "stroke_width": 1,
                "effect": "none",
                "max_width_ratio": 0.82,
                "max_lines": 2,
                "band_height_ratio": 0.07,
            },
        ],
    },
]

BUILTIN_TEMPLATES: list[dict] = [*_CLASSIC, *_CUTOUT]
